//
//  CardsWorker.swift
//  DesafioHearthstone
//
//  Created by Ricardo Bailoni on 09/04/20.
//  Copyright (c) 2020 Ricardo Bailoni. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

fileprivate struct Constants {
    static let pathCardsURL = "cards/"
    
    private init() {}
}

class CardsWorker {
    func fetchCardsDeck(session: String, name: String, completion: @escaping (Result<[CardsResponse], ResponseError>) -> Void) {
        HearthstoneAPI.shared.fetchResourceArray(path: Constants.pathCardsURL + "\(session.lowercased())/\(name)", completion: completion)
    }
}
