//
//  CardsInteractor.swift
//  DesafioHearthstone
//
//  Created by Ricardo Bailoni on 09/04/20.
//  Copyright (c) 2020 Ricardo Bailoni. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardsBusinessLogic {
    func doSomething(request: Cards.Something.Request)
}

protocol CardsDataStore {
    var sessionSelected: String? { get set }
    var nameSelected: String? { get set }
}

class CardsInteractor: CardsBusinessLogic, CardsDataStore {
    var presenter: CardsPresentationLogic?
    var worker: CardsWorker?
    var nameSelected: String?
    var sessionSelected: String?

    // MARK: Do something
    
    func doSomething(request: Cards.Something.Request) {
        worker = CardsWorker()
        worker?.doSomeWork()
        
        let response = Cards.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
