//
//  CardsModels.swift
//  DesafioHearthstone
//
//  Created by Ricardo Bailoni on 09/04/20.
//  Copyright (c) 2020 Ricardo Bailoni. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Cards {
    enum CardsDeck {
        struct Request {
        }
        struct Response {
            var result: Result<[CardsResponse], ResponseError>
            var deckSelected: String
        }
        struct ViewModel {
            var pathCards: [String]
            var deckSelected: String
        }
    }
}
