//
//  HomeModels.swift
//  DesafioHearthstone
//
//  Created by Ricardo Bailoni on 09/04/20.
//  Copyright (c) 2020 Ricardo Bailoni. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    enum DeckSessions {
        struct Request {
            
        }
        struct Response {
            var result: Result<InfoResponse, ResponseError>
        }
        struct ViewModel {
            var sessions: Dictionary<String, [String]>?
        }
    }
}
